name: Build

on:
  pull_request:
    branches: [main]

concurrency:
  group: build-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      push: false
